name: "Travel Calculator"
author: "Manuel Santibanez"
description: "Calculate the cost of a trip"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "blue"
  icon: "map"
inputs:
  email: 
    description: "Email"
    required: true
    default: ${{ github.actor }}@localhost
name:
  description: The committer's name
  required: true
  default: "Manuel"
  type: "string"
  secret: false
  min_length: 3
  max_length: 10
  pattern: "^[a-zA-Z]+$"
  error_message: "Name must be a string with only letters"
  display_name: "Your Name"
  display_order: 1
  display_secret: false
  display_required: true
  display_default: "Manuel"
  display_description: "Your name"
  display_min_length: 3
  display_max_length: 10
  display_pattern: "^[a-zA-Z]+$"
  display_error_message: "Name must be a string with only letters"