name: Travel Calculator
author: Manuel Santibanez
description: Calculate the cost of a trip

# Workflow configuration
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: user/repo:latest

      - name: Run Travel Calculator
        run: docker run -e GITHUB_ACTOR=${{ github.actor }} -e INPUT_EMAIL=${{ inputs.email }} user/repo:latest
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          INPUT_EMAIL: ${{ inputs.email }}

# Action configuration for reusable workflows
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  color: blue
  icon: map

inputs:
  email:
    description: "Email"
    required: true
    default: "${{ github.actor }}@localhost"
    type: string

  name:
    description: "The committer's name"
    required: true
    default: "Manuel"
    type: string
    minLength: 3
    maxLength: 10
    pattern: "^[a-zA-Z]+$"
    errorMessage: "Name must be a string with only letters"
