name: Travel Calculator
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: travel-calculator:latest
          load: true  # This loads the image into the Docker daemon

      - name: Run Travel Calculator
        run: |
          docker images  # List available images for debugging
          docker run --rm -e GITHUB_ACTOR=${{ github.actor }} -e INPUT_EMAIL=${{ github.event.inputs.email }} travel-calculator:latest
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          INPUT_EMAIL: ${{ github.event.inputs.email }}