name: Travel Calculator

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Update to the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Update to the latest version

      - name: Build and push Docker image
        uses: docker/build-push-action@v3 # Update to the latest version
        with:
          context: .
          file: ./Dockerfile
          tags: user/repo:latest

      - name: Run Travel Calculator
        run: docker run -e GITHUB_ACTOR=${{ github.actor }} -e INPUT_EMAIL=${{ inputs.email }} user/repo:latest
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          INPUT_EMAIL: ${{ inputs.email }}
